### ISSUE TITLE
Add a licensing disclaimer in the Readme

### ISSUE THREAD

**Issue by kitoaken** [laurirasanen/BridgeSource2Plugin#11]
New Quixel users often don't know Megascans are free for Unreal Engine use only. Using the assets in S2 will need a subscription from here:
https://quixel.com/pricing

Nothing wrong with the tool itself, it'd just be useful to have a notice for new Quixel/Source users (especially with s&box releasing this year)

**Comment by laurirasanen** [comment]
Added a notice to the readme in https://github.com/laurirasanen/BridgeSource2Plugin/commit/9f8503dbdee07dbec9d79df0e2afe9c0a3245db4.
